- name: Get a valid destination compute hostname
  pause:
    prompt: "\e[1;96mPlease choose a valid destination compute hostname from the above list - ex of a valid hostname:\e[1;93m929235-compute004.localdomain"
  register: dsthost
  until: (dsthost.user_input in id.stdout_lines) != -1
  retries: 5
  delay: 2

- name: validate destination compute hostname
  ansible.builtin.debug:
    msg: 'You have entered a valid destination compute hostname: {{ dsthost.user_input }}'
